name: CI

on: [push, pull_request]

jobs:
  php74:
    name: "php 7.4"
    runs-on: ubuntu-latest
    container: "nofutur3/php-tests:7.4"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: composer install --no-interaction

      - name: Run static analysis
        run: vendor/bin/phpstan analyse

  php80:
    name: "php 8.0"
    runs-on: ubuntu-latest
    container: "nofutur3/php-tests:8.0"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: composer install --no-interaction

      - name: Run static analysis
        run: vendor/bin/phpstan analyse

  php81laravel80:
    name: "php 8.1 and laravel 8.0"
    runs-on: ubuntu-latest
    container: "nofutur3/php-tests:8.1"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: composer update --no-interaction --with illuminate/contracts:^8.0

      - name: Run static analysis
        run: vendor/bin/phpstan analyse

  php81:
    name: "php 8.1"
    runs-on: ubuntu-latest
    container: "nofutur3/php-tests:8.1"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: composer install --no-interaction

      - name: Chesk code style
        run: vendor/bin/php-cs-fixer fix --dry-run --no-interaction

      - name: Run static analysis
        run: vendor/bin/phpstan analyse
